[package]
name = "rust-tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
softbuffer = "0.4.1"
tiny-skia = "0.11.4"
winit = "0.29.15"
